"""
Chunk quality invariants for production scraper output.

Loads all bcn-*.json files generated by test_scrape_to_chunks_e2e.py and
validates structural invariants that must always hold regardless of norm type.
"""

import json
import glob
import os
import re
import sys
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

CHUNKS_DIR = "tests/test_diverse_output/chunks"
XMLS_DIR = "tests/test_diverse_output/xmls"
REQUIRED_TOP_FIELDS = {"norm_id", "norm_type", "norm_number", "formal_citation",
                        "title", "publication_date", "official_url", "source",
                        "chunks", "total_chunks", "total_articles", "vigentes"}
VALID_FORCE_STATUS = {"active", "repealed", "deferred"}
REMOVED_METADATA_FIELDS = {"literal_text", "subdivisions", "path"}
MIN_CONTENT_AFTER_HEADER = 20  # chars (Constitución Art. 4 is a legitimate 49-char article)
MAX_ALLOWED_RECONSTRUCTION_DIFF = 15  # chars, accounts for whitespace normalization only

# A complete Chilean legal article always closes on sentence-terminating
# punctuation. Anything else means the text was cut off -- either by BCN's own
# XML export or by our chunking.
SENTENCE_TERMINATORS = '.;:!?)"”'
# Repealed/suppressed articles are legitimately a bare marker with no terminator
REPEAL_MARKER_PATTERN = re.compile(
    r'^\s*(?:Art[í\wi]*\.?\s*[\wº°.\-]*\s*[.\-]*\s*)?'
    r'(?:Derogado|Suprimido|Eliminado|Sin efecto)\s*\.?\s*$',
    re.IGNORECASE,
)
# BCN renders amendment history in a right-hand margin column. If any of these
# leak into the embedded body the chunk is contaminated (and words get split).
MARGIN_NOTE_PATTERN = re.compile(
    r'(D\.\s*O\.\s*\d{2}\.\d{2}\.\d{4}'
    r'|LEY\s+N[°º]?\s*[\d.]{5,}'
    r'|CPR\s+Art\.)'
)
# token_count must be a believable estimate of the chunk text, not a stale or
# defaulted number. Spanish legal prose runs ~3-6 chars/token.
MIN_CHARS_PER_TOKEN = 1.5
MAX_CHARS_PER_TOKEN = 12.0


def load_all_chunk_files():
    files = glob.glob(f"{CHUNKS_DIR}/bcn-*.json")
    assert len(files) > 0, f"No chunk files found in {CHUNKS_DIR}"
    results = []
    for f in files:
        with open(f, "r", encoding="utf-8") as fh:
            results.append((f, json.load(fh)))
    return results


@pytest.fixture(scope="module")
def all_docs():
    return load_all_chunk_files()


def test_top_level_schema(all_docs):
    for filepath, doc in all_docs:
        missing = REQUIRED_TOP_FIELDS - set(doc.keys())
        assert not missing, f"{filepath}: missing top-level fields: {missing}"
        assert doc["total_chunks"] == len(doc["chunks"]), \
            f"{filepath}: total_chunks={doc['total_chunks']} but len(chunks)={len(doc['chunks'])}"


def test_chunk_schema(all_docs):
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            assert isinstance(chunk.get("chunk_index"), int), f"{filepath}: chunk missing int chunk_index"
            assert isinstance(chunk.get("token_count"), int), f"{filepath}: chunk missing int token_count"
            assert isinstance(chunk.get("content"), str), f"{filepath}: chunk missing string content"
            assert isinstance(chunk.get("metadata"), dict), f"{filepath}: chunk missing dict metadata"


def test_no_empty_content(all_docs):
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            content = chunk["content"]
            assert content.strip(), \
                f"{filepath}: chunk {chunk['chunk_index']} has empty content"


def test_content_has_real_text_after_header(all_docs):
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            if chunk["metadata"].get("force_status") != "active":
                # Repealed/deferred articles legitimately have minimal text (e.g. "Derogado")
                continue
            content = chunk["content"]
            # Header ends at first double-newline or after first line
            # Find where actual article text starts
            if "\n\n" in content:
                body = content.split("\n\n", 1)[1]
            elif "\n" in content:
                body = content.split("\n", 1)[1]
            else:
                body = content
            assert len(body.strip()) >= MIN_CONTENT_AFTER_HEADER, \
                f"{filepath}: chunk {chunk['chunk_index']} has only header, no real content " \
                f"(body length: {len(body.strip())} chars)"


def test_no_duplicate_content(all_docs):
    for filepath, doc in all_docs:
        contents = [chunk["content"] for chunk in doc["chunks"]]
        seen = set()
        for i, c in enumerate(contents):
            assert c not in seen, \
                f"{filepath}: chunk {i} has duplicate content with earlier chunk"
            seen.add(c)


def _body_without_header(content: str) -> str:
    if "\n\n" in content:
        return content.split("\n\n", 1)[1].strip()
    if "\n" in content:
        return content.split("\n", 1)[1].strip()
    return content.strip()


def test_no_duplicate_body_content(all_docs):
    """Catches repeated article text even if headers differ (e.g. same body, different citation)."""
    for filepath, doc in all_docs:
        seen = {}
        for chunk in doc["chunks"]:
            body = _body_without_header(chunk["content"])
            if not body:
                continue
            idx = chunk["chunk_index"]
            assert body not in seen, \
                f"{filepath}: chunk {idx} has the same body content as chunk {seen[body]} (repeated text)"
            seen[body] = idx


def test_fragment_sequence_is_not_truncated(all_docs):
    """
    When a large article/subdivision is split into fragments, verify the full
    sequence is present: fragment_index values must be unique, run 1..N with no
    gaps, and match total_fragments -- a missing index means a fragment was
    silently dropped (truncated) during chunking.
    """
    for filepath, doc in all_docs:
        groups = {}
        for chunk in doc["chunks"]:
            meta = chunk["metadata"]
            if not meta.get("is_fragment"):
                continue
            key = (meta.get("part_id"), meta.get("fragment_of"))
            groups.setdefault(key, []).append(chunk)

        for key, group_chunks in groups.items():
            fragment_indices = sorted(
                c["metadata"]["fragment_index"] for c in group_chunks
                if c["metadata"].get("fragment_index") is not None
            )
            if not fragment_indices:
                continue
            total_fragments_values = {
                c["metadata"].get("total_fragments") for c in group_chunks
                if c["metadata"].get("total_fragments") is not None
            }
            assert len(total_fragments_values) <= 1, \
                f"{filepath}: fragment group {key} has inconsistent total_fragments: {total_fragments_values}"
            expected = list(range(1, len(fragment_indices) + 1))
            assert fragment_indices == expected, \
                f"{filepath}: fragment group {key} has non-sequential/missing fragment_index: {fragment_indices} " \
                f"(possible truncated/dropped fragment)"
            if total_fragments_values:
                declared_total = next(iter(total_fragments_values))
                assert declared_total == len(fragment_indices), \
                    f"{filepath}: fragment group {key} declares total_fragments={declared_total} " \
                    f"but only {len(fragment_indices)} fragments found (some may have been dropped)"


def test_chunk_index_sequential(all_docs):
    for filepath, doc in all_docs:
        indices = [chunk["chunk_index"] for chunk in doc["chunks"]]
        expected = list(range(len(doc["chunks"])))
        assert indices == expected, \
            f"{filepath}: chunk_index not sequential: got {indices[:10]}... expected {expected[:10]}..."


def test_metadata_required_fields(all_docs):
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            meta = chunk["metadata"]
            idx = chunk["chunk_index"]
            assert meta.get("article_label"), \
                f"{filepath}: chunk {idx} missing article_label"
            assert isinstance(meta.get("in_force"), bool), \
                f"{filepath}: chunk {idx} in_force is not boolean: {meta.get('in_force')}"
            assert meta.get("force_status") in VALID_FORCE_STATUS, \
                f"{filepath}: chunk {idx} invalid force_status: {meta.get('force_status')}"
            assert meta.get("formatted_citation"), \
                f"{filepath}: chunk {idx} missing formatted_citation"


def test_force_status_consistency(all_docs):
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            meta = chunk["metadata"]
            idx = chunk["chunk_index"]
            if meta.get("force_status") == "active":
                assert meta.get("in_force") is True, \
                    f"{filepath}: chunk {idx} force_status=active but in_force={meta.get('in_force')}"
            elif meta.get("force_status") in ("repealed", "deferred"):
                assert meta.get("in_force") is False, \
                    f"{filepath}: chunk {idx} force_status={meta['force_status']} but in_force={meta.get('in_force')}"


def test_removed_fields_not_present(all_docs):
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            meta = chunk["metadata"]
            present = REMOVED_METADATA_FIELDS & set(meta.keys())
            assert not present, \
                f"{filepath}: chunk {chunk['chunk_index']} still has removed fields: {present}"


def _strip_notes(text: str) -> str:
    text = re.sub(r'\[Fragmento[^\]]*\]\n*', '', text)
    text = re.sub(r'\[Parte[^\]]*\]\n*', '', text)
    text = re.sub(r'\[Texto final[^\]]*\]\n*', '', text)
    text = re.sub(r'\[NOTA:[^\]]*\]', '', text)
    return text


def _body_raw(content: str) -> str:
    """Like _body_without_header but keeps surrounding whitespace, so fragments
    can be concatenated without losing the spacing between them."""
    if "\n\n" in content:
        return content.split("\n\n", 1)[1]
    if "\n" in content:
        return content.split("\n", 1)[1]
    return content


def _articles_by_part_id(doc):
    """Groups chunks by the article they came from, in chunk_index order."""
    groups = {}
    for chunk in doc["chunks"]:
        part_id = chunk["metadata"].get("part_id")
        if part_id is None:
            continue
        groups.setdefault(str(part_id), []).append(chunk)
    for group in groups.values():
        group.sort(key=lambda c: c["chunk_index"])
    return groups


def _reconstruct_article_text(group_chunks) -> str:
    text = "".join(_body_raw(c["content"]) for c in group_chunks)
    return re.sub(r"\s+", " ", _strip_notes(text)).strip()


def test_articles_not_truncated(all_docs):
    """
    Reconstructs each article and asserts it closes on sentence-terminating
    punctuation.

    This is the only check that can catch content truncated *at the source*:
    BCN's XML export silently cuts some articles mid-word (e.g. Constitución
    Art. 107 ends at "disposició", Art. 19 ends at a dangling "20º" dropping
    numerals 20-26). test_no_content_lost_vs_original_xml compares our output
    against that same truncated XML, so it passes on already-lost text --
    it validates fidelity to the fetch, not completeness of the article.
    """
    for filepath, doc in all_docs:
        truncated = []
        for part_id, group_chunks in _articles_by_part_id(doc).items():
            statuses = {c["metadata"].get("force_status") for c in group_chunks}
            if statuses and "active" not in statuses:
                # Repealed/deferred articles legitimately carry no closing text
                continue
            text = _reconstruct_article_text(group_chunks)
            if not text or REPEAL_MARKER_PATTERN.match(text):
                continue
            if text[-1] not in SENTENCE_TERMINATORS:
                label = group_chunks[0]["metadata"].get("article_label")
                truncated.append(f"art. {label} (part_id {part_id}) ends: ...{text[-60:]!r}")

        assert not truncated, (
            f"{filepath}: {len(truncated)} article(s) do not end on sentence-terminating "
            f"punctuation, i.e. their text is cut off:\n  " + "\n  ".join(truncated)
        )


def test_no_margin_notes_in_body(all_docs):
    """
    BCN's XML puts amendment history ("D.O. 17.08.1989", "LEY N° 20.050") in a
    right-hand margin column of the same <Texto> block. If _strip_margin_notes()
    misses one it lands in the embedded text, splitting words across it and
    polluting the vector.
    """
    for filepath, doc in all_docs:
        contaminated = []
        for chunk in doc["chunks"]:
            match = MARGIN_NOTE_PATTERN.search(_body_without_header(chunk["content"]))
            if match:
                contaminated.append(
                    f"chunk {chunk['chunk_index']} (art. {chunk['metadata'].get('article_label')}): "
                    f"{match.group(0)!r}"
                )
        assert not contaminated, (
            f"{filepath}: {len(contaminated)} chunk(s) contain unstripped BCN margin notes "
            f"in the embedded body:\n  " + "\n  ".join(contaminated)
        )


def test_formatted_citation_unique(all_docs):
    """
    formatted_citation is what the MCP tool shows the user to identify a passage.
    Two chunks with different text under the same citation make the answer
    unverifiable. Catches articles that restart their numbering mid-way (e.g.
    Constitución Art. 144 has two separate "1." to "5." lists).
    """
    for filepath, doc in all_docs:
        seen = {}
        collisions = []
        for chunk in doc["chunks"]:
            citation = chunk["metadata"].get("formatted_citation")
            if not citation:
                continue
            idx = chunk["chunk_index"]
            if citation in seen:
                collisions.append(f"chunks {seen[citation]} and {idx}: {citation!r}")
            else:
                seen[citation] = idx
        assert not collisions, (
            f"{filepath}: {len(collisions)} duplicated formatted_citation(s) -- distinct "
            f"passages are indistinguishable to the user:\n  " + "\n  ".join(collisions)
        )


def test_every_chunk_has_part_id(all_docs):
    """
    The XML cross-check tests skip chunks without part_id. Without this guard a
    regression that stops emitting part_id would make those tests pass vacuously.
    """
    for filepath, doc in all_docs:
        orphans = [c["chunk_index"] for c in doc["chunks"] if c["metadata"].get("part_id") is None]
        assert not orphans, \
            f"{filepath}: {len(orphans)} chunk(s) have no part_id: {orphans[:10]} " \
            f"-- these are invisible to the XML completeness checks"


def test_article_and_vigente_counters_match_chunks(all_docs):
    """total_articles/vigentes are the numbers used to report progress and to
    sanity-check production output, so they must agree with the chunks."""
    for filepath, doc in all_docs:
        groups = _articles_by_part_id(doc)
        assert doc["total_articles"] == len(groups), \
            f"{filepath}: total_articles={doc['total_articles']} but chunks cover " \
            f"{len(groups)} distinct articles"

        in_force_articles = sum(
            1 for group in groups.values()
            if any(c["metadata"].get("in_force") for c in group)
        )
        assert doc["vigentes"] == in_force_articles, \
            f"{filepath}: vigentes={doc['vigentes']} but {in_force_articles} distinct " \
            f"articles have in_force=True"
        assert doc["vigentes"] <= doc["total_articles"], \
            f"{filepath}: vigentes={doc['vigentes']} exceeds total_articles={doc['total_articles']}"


def test_token_count_is_plausible(all_docs):
    """A defaulted or stale token_count silently breaks embedding batch sizing
    (29 chunks/request is tuned against it) and the daily quota accounting."""
    for filepath, doc in all_docs:
        for chunk in doc["chunks"]:
            idx, tokens, length = chunk["chunk_index"], chunk["token_count"], len(chunk["content"])
            assert tokens > 0, f"{filepath}: chunk {idx} has token_count={tokens}"
            ratio = length / tokens
            assert MIN_CHARS_PER_TOKEN <= ratio <= MAX_CHARS_PER_TOKEN, \
                f"{filepath}: chunk {idx} token_count={tokens} is implausible for " \
                f"{length} chars ({ratio:.1f} chars/token)"


def test_no_placeholder_article_label(all_docs):
    """
    Regression guard: articles without <NombreParte> used to fall back to the
    literal label "Contenido", producing citations like "art. Contenido". The
    fallback must resolve a real name from <TituloParte>.
    """
    for filepath, doc in all_docs:
        placeholders = [
            f"chunk {c['chunk_index']}: {c['metadata'].get('formatted_citation')!r}"
            for c in doc["chunks"]
            if str(c["metadata"].get("article_label", "")).strip().lower() in {"contenido", "", "none"}
        ]
        assert not placeholders, (
            f"{filepath}: {len(placeholders)} chunk(s) have a placeholder article_label "
            f"instead of a real article name:\n  " + "\n  ".join(placeholders[:10])
        )


def test_norm_id_matches_filename(all_docs):
    """Guards against a norm's chunks being written under another norm's S3 key."""
    for filepath, doc in all_docs:
        expected = os.path.basename(filepath).removeprefix("bcn-").removesuffix(".json")
        assert str(doc["norm_id"]) == expected, \
            f"{filepath}: norm_id={doc['norm_id']} does not match filename id {expected}"


def test_article_count_matches_xml(all_docs):
    """
    Counts real articles (regular + transitory) that the XML parser's hierarchy
    extraction identifies in the original BCN XML -- excluding section-heading
    containers that merely wrap real articles as children (e.g. a "DISPOSICIONES
    TRANSITORIAS" divider) -- and compares against the distinct articles
    represented in the chunk JSON (by part_id). Catches whole articles silently
    dropped during chunking (e.g. skipped between two chunk_index values) that
    per-article content checks can't see, since those only compare articles that
    already made it into a chunk.
    """
    from core.xml_parser import BCNXMLParser

    parser = BCNXMLParser()

    for filepath, doc in all_docs:
        norm_id = doc["norm_id"]
        xml_path = f"{XMLS_DIR}/norm_{norm_id}.xml"
        if not os.path.exists(xml_path):
            pytest.skip(f"No XML available for norm {norm_id} to cross-check against")
            continue

        with open(xml_path, "r", encoding="utf-8") as fh:
            xml_content = fh.read()

        hierarchy = parser.extract_article_hierarchy(xml_content, norm_id)
        xml_article_ids = set(hierarchy.keys())

        json_part_ids = {
            chunk["metadata"].get("part_id")
            for chunk in doc["chunks"]
            if chunk["metadata"].get("part_id") is not None
        }
        # part_id may be int or str depending on serialization; normalize to str for comparison
        json_part_ids = {str(pid) for pid in json_part_ids}

        missing = xml_article_ids - json_part_ids
        # Treaty annexes with detectable per-article structure are split by the chunker
        # into synthetic sub-keys ("anexo_X_art1", "anexo_X_art2", ...) that replace the
        # single "anexo_X" hierarchy key -- that's an intentional split, not a drop.
        missing = {
            key for key in missing
            if not (key.startswith("anexo_") and any(pid.startswith(f"{key}_art") for pid in json_part_ids))
        }
        assert not missing, \
            f"{filepath}: {len(missing)} article(s) present in XML but missing from chunk JSON " \
            f"(idParte values: {sorted(missing)}) -- possible dropped article during chunking"


def test_no_content_lost_vs_original_xml(all_docs):
    """
    Reconstructs each article's full text from its chunks (in chunk_index order,
    stripping headers/fragment notes) and compares it against the article text
    extracted directly from the original BCN XML. Catches truncation/dropped
    content that per-chunk checks can't see (e.g. text before the first
    subdivision, after the last one, or a fragment silently dropped mid-split).
    """
    from core.xml_parser import BCNXMLParser

    for filepath, doc in all_docs:
        norm_id = doc["norm_id"]
        xml_path = f"{XMLS_DIR}/norm_{norm_id}.xml"
        if not os.path.exists(xml_path):
            pytest.skip(f"No XML available for norm {norm_id} to cross-check against")
            continue

        with open(xml_path, "r", encoding="utf-8") as fh:
            xml_content = fh.read()

        parser = BCNXMLParser()
        original_texts = parser.extract_article_texts(xml_content)

        groups = {}
        for chunk in doc["chunks"]:
            part_id = chunk["metadata"].get("part_id")
            if part_id is None:
                continue
            groups.setdefault(part_id, []).append(chunk)

        for part_id, group_chunks in groups.items():
            if part_id not in original_texts:
                continue
            group_sorted = sorted(group_chunks, key=lambda c: c["chunk_index"])
            reconstructed = "".join(_body_raw(c["content"]) for c in group_sorted)
            reconstructed = _strip_notes(reconstructed)

            original_norm = re.sub(r"\s+", " ", original_texts[part_id]).strip()
            reconstructed_norm = re.sub(r"\s+", " ", reconstructed).strip()

            diff = len(original_norm) - len(reconstructed_norm)
            assert abs(diff) <= MAX_ALLOWED_RECONSTRUCTION_DIFF, \
                f"{filepath}: part_id {part_id} reconstructed text differs from original XML " \
                f"by {diff} chars (original={len(original_norm)}, reconstructed={len(reconstructed_norm)}) " \
                f"-- possible truncated/dropped content"
